use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use codenoesis_contracts::{
    CodeNoesisErrorV5, DocumentationContractError, QueryContractError, generate_documentation_v1,
    local_query_result_v1, validate_documentation_bundle_v1, validate_stored_snapshot_semantic_v4,
};
use codenoesis_domain::s4::WorkspaceError;
use codenoesis_domain::storage::{
    ArtifactRole, EXTRACTION_HASH_DOMAIN_V2, GRAPH_HASH_DOMAIN_V2, LocalSnapshotHead,
    SNAPSHOT_HASH_DOMAIN_V4, SNAPSHOT_SCHEMA_VERSION_V4, SemanticHash, SnapshotId, StoredArtifact,
};
use codenoesis_domain::{ObjectId, RepositoryIdentity};
use serde_json::Value;

#[test]
fn gt_fr_doc_001_deterministic_markdown() {
    let fixture =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/s4/workspace-docs-v1");
    let semantic: Value = serde_json::from_slice(
        &fs::read(fixture.join("expected-snapshot-semantic.json")).expect("snapshot semantic"),
    )
    .expect("snapshot semantic JSON");
    let generated = generate_documentation_v1(
        &semantic,
        "urn:codenoesis:snapshot:blake3:832888db94f6bf06da375a1cfc055a7c9b80d624b0596a1e45d1f9c646af9b8f",
        "6ed66dd0d5bf2451087fcb17c254048084d9d0f1bd2ea51062d46a38d1defe31",
    )
    .expect("generate reviewed documentation");
    let expected_manifest: Value = serde_json::from_slice(
        &fs::read(fixture.join("expected-documentation-manifest.json"))
            .expect("documentation manifest"),
    )
    .expect("documentation manifest JSON");
    assert_eq!(generated.manifest(), &expected_manifest);
    for document in generated.documents() {
        assert_eq!(
            document.bytes,
            fs::read(fixture.join("expected-docs").join(&document.path))
                .expect("reviewed Markdown"),
            "generated bytes changed for {}",
            document.path
        );
    }
    let bytes = generated
        .documents()
        .iter()
        .map(|document| (document.path.clone(), document.bytes.clone()))
        .collect::<BTreeMap<_, _>>();
    validate_documentation_bundle_v1(
        generated.manifest(),
        &bytes,
        "urn:codenoesis:fixture:s4-workspace-docs-v1",
        "urn:codenoesis:snapshot:blake3:832888db94f6bf06da375a1cfc055a7c9b80d624b0596a1e45d1f9c646af9b8f",
        "6ed66dd0d5bf2451087fcb17c254048084d9d0f1bd2ea51062d46a38d1defe31",
    )
    .expect("validate statement grounding and exact bytes");
}

#[test]
fn e2e_fr_qry_001_exact_id_results() {
    let fixture =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/s4/workspace-docs-v1");
    let semantic = read_json(&fixture.join("expected-snapshot-semantic.json"));
    let manifest = read_json(&fixture.join("expected-documentation-manifest.json"));
    let snapshot_id = "urn:codenoesis:snapshot:blake3:832888db94f6bf06da375a1cfc055a7c9b80d624b0596a1e45d1f9c646af9b8f";
    for (requested_id, expected) in [
        (
            "urn:codenoesis:entity:blake3:18bd97153a41f322136e8f93573877bfc1a2f43fabc6564b789e979a6cffcafa",
            "expected-query-entity.json",
        ),
        (
            "urn:codenoesis:document:blake3:4d6e3c7a3442af14614b515c93197302e23744d004ec671abc4bbab4ae402a99",
            "expected-query-document.json",
        ),
    ] {
        let result = local_query_result_v1(&semantic, &manifest, snapshot_id, requested_id)
            .expect("build reviewed exact-ID query")
            .canonical_stdout()
            .expect("serialize reviewed exact-ID query");
        assert_eq!(
            serde_json::from_slice::<Value>(&result).expect("query result JSON"),
            read_json(&fixture.join(expected))
        );
    }
    for (path, kind) in [
        ("/knowledge_graph/claims/0/id", "claim"),
        ("/knowledge_graph/evidence/0/id", "evidence"),
    ] {
        let requested_id = semantic
            .pointer(path)
            .and_then(Value::as_str)
            .expect("reviewed exact-ID record");
        let result = local_query_result_v1(&semantic, &manifest, snapshot_id, requested_id)
            .expect("query reviewed exact ID")
            .canonical_stdout()
            .expect("serialize exact-ID query");
        assert_eq!(
            serde_json::from_slice::<Value>(&result).expect("query result JSON")["result_kind"],
            kind
        );
    }
    assert!(matches!(
        local_query_result_v1(
            &semantic,
            &manifest,
            snapshot_id,
            "urn:codenoesis:entity:blake3:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        ),
        Err(QueryContractError::NotFound)
    ));
}

#[test]
fn conf_fr_cli_001_reviewed_v5_errors_are_exact() {
    let fixture =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/s4/workspace-docs-v1");
    for (actual, expected) in [
        (
            CodeNoesisErrorV5::from_workspace(&WorkspaceError::UnsupportedWorkspace),
            "expected-error-unsupported-workspace.json",
        ),
        (
            CodeNoesisErrorV5::docs_unmarked_nonempty_root(),
            "expected-error-unmarked-output.json",
        ),
    ] {
        assert_eq!(
            serde_json::from_slice::<Value>(
                &actual
                    .canonical_stderr()
                    .expect("serialize reviewed V5 error")
            )
            .expect("V5 error JSON"),
            read_json(&fixture.join(expected))
        );
    }
}

#[test]
fn fr_sto_001_loaded_s4_semantic_must_match_every_head_artifact() {
    let fixture =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/s4/workspace-docs-v1");
    let semantic = read_json(&fixture.join("expected-snapshot-semantic.json"));
    let head = reviewed_head(&semantic);
    validate_stored_snapshot_semantic_v4(&semantic, &head).expect("reviewed S4 store binding");

    let mut corrupted = semantic;
    corrupted["knowledge_graph"]["semantic_hash"]["value"] = Value::String("0".repeat(64));
    assert!(validate_stored_snapshot_semantic_v4(&corrupted, &head).is_err());
}

#[test]
fn fr_doc_003_document_limits_plus_one_fail_closed() {
    let fixture =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/s4/workspace-docs-v1");
    let manifest = read_json(&fixture.join("expected-documentation-manifest.json"));
    let snapshot_id = "urn:codenoesis:snapshot:blake3:832888db94f6bf06da375a1cfc055a7c9b80d624b0596a1e45d1f9c646af9b8f";
    let snapshot_hash = "6ed66dd0d5bf2451087fcb17c254048084d9d0f1bd2ea51062d46a38d1defe31";
    let documents = manifest["documents"]
        .as_array()
        .expect("reviewed documents")
        .iter()
        .map(|document| {
            let path = document["path"].as_str().expect("reviewed document path");
            (
                path.to_owned(),
                fs::read(fixture.join("expected-docs").join(path)).expect("reviewed document"),
            )
        })
        .collect::<BTreeMap<_, _>>();

    let mut oversized_document = documents.clone();
    oversized_document.insert("overview.md".to_owned(), vec![b'x'; 1_048_577]);
    assert_eq!(
        validate_documentation_bundle_v1(
            &manifest,
            &oversized_document,
            "urn:codenoesis:fixture:s4-workspace-docs-v1",
            snapshot_id,
            snapshot_hash,
        ),
        Err(DocumentationContractError::LimitExceeded)
    );

    let mut oversized_manifest = manifest;
    oversized_manifest["documents"] = Value::Array(vec![Value::Null; 2_002]);
    let oversized_set = (0..2_002)
        .map(|ordinal| (format!("modules/{ordinal}.md"), vec![b'x']))
        .collect::<BTreeMap<_, _>>();
    assert_eq!(
        validate_documentation_bundle_v1(
            &oversized_manifest,
            &oversized_set,
            "urn:codenoesis:fixture:s4-workspace-docs-v1",
            snapshot_id,
            snapshot_hash,
        ),
        Err(DocumentationContractError::LimitExceeded)
    );
}

#[test]
fn fr_qry_001_query_result_limit_plus_one_fails_closed() {
    let fixture =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/s4/workspace-docs-v1");
    let mut semantic = read_json(&fixture.join("expected-snapshot-semantic.json"));
    let manifest = read_json(&fixture.join("expected-documentation-manifest.json"));
    let entity_id = "urn:codenoesis:entity:blake3:18bd97153a41f322136e8f93573877bfc1a2f43fabc6564b789e979a6cffcafa";
    let entity = semantic["knowledge_graph"]["entities"]
        .as_array_mut()
        .expect("reviewed entities")
        .iter_mut()
        .find(|entity| entity["id"].as_str() == Some(entity_id))
        .expect("reviewed query entity");
    entity["properties"]["oversized"] = Value::String("x".repeat(4_194_304));

    assert!(matches!(
        local_query_result_v1(
            &semantic,
            &manifest,
            "urn:codenoesis:snapshot:blake3:832888db94f6bf06da375a1cfc055a7c9b80d624b0596a1e45d1f9c646af9b8f",
            entity_id,
        ),
        Err(QueryContractError::LimitExceeded)
    ));
}

fn read_json(path: &Path) -> Value {
    serde_json::from_slice(&fs::read(path).expect("fixture JSON")).expect("valid fixture JSON")
}

fn reviewed_head(semantic: &Value) -> LocalSnapshotHead {
    let snapshot_hash = "6ed66dd0d5bf2451087fcb17c254048084d9d0f1bd2ea51062d46a38d1defe31";
    let graph_hash = semantic["knowledge_graph"]["semantic_hash"]["value"]
        .as_str()
        .expect("reviewed graph hash");
    let mut artifacts = vec![
        StoredArtifact::new(
            ArtifactRole::SnapshotSemantic,
            0,
            serde_json::to_vec(semantic).expect("snapshot semantic"),
            SemanticHash::blake3(SNAPSHOT_HASH_DOMAIN_V4, snapshot_hash),
        ),
        StoredArtifact::new(
            ArtifactRole::KnowledgeGraph,
            0,
            serde_json::to_vec(&semantic["knowledge_graph"]).expect("knowledge graph"),
            SemanticHash::blake3(GRAPH_HASH_DOMAIN_V2, graph_hash),
        ),
    ];
    artifacts.extend(
        semantic["extraction_chunks"]
            .as_array()
            .expect("reviewed extraction chunks")
            .iter()
            .enumerate()
            .map(|(ordinal, chunk)| {
                StoredArtifact::new(
                    ArtifactRole::ExtractionChunk,
                    u32::try_from(ordinal).expect("reviewed extraction ordinal"),
                    serde_json::to_vec(chunk).expect("extraction chunk"),
                    SemanticHash::blake3(
                        EXTRACTION_HASH_DOMAIN_V2,
                        chunk["semantic_hash"]["value"]
                            .as_str()
                            .expect("reviewed extraction hash"),
                    ),
                )
            }),
    );
    LocalSnapshotHead {
        repository_identity: RepositoryIdentity::parse(
            "urn:codenoesis:fixture:s4-workspace-docs-v1",
        )
        .expect("reviewed repository identity"),
        snapshot_id: SnapshotId::from_semantic_hash(snapshot_hash).expect("reviewed snapshot ID"),
        commit_oid: ObjectId::parse_sha1("c09d8c24e4704036c31b4f42e2f4df6e4acd347f")
            .expect("reviewed commit"),
        snapshot_schema_version: SNAPSHOT_SCHEMA_VERSION_V4.to_owned(),
        semantic_hash: SemanticHash::blake3(SNAPSHOT_HASH_DOMAIN_V4, snapshot_hash),
        graph_semantic_hash: SemanticHash::blake3(GRAPH_HASH_DOMAIN_V2, graph_hash),
        generation: 1,
        artifacts: artifacts.iter().map(Into::into).collect(),
    }
}
