version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:13"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:29"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    labels:
      - dependencies
